# Config relating to the Lazygit UI
gui:
  # Nerd fonts version to use.
  # One of: '2' | '3' | empty string (default)
  # If empty, do not show icons.
  nerdFontsVersion: "3"

  # If true (default), file icons are shown in the file views. Only relevant if NerdFontsVersion is not empty.
  showFileIcons: true

customCommands:
  - key: <c-a>
    description: Pick AI commit
    command: aicommit2 -a -y
    context: files
    subprocess: true
    showOutput: true
  - key: <c-n>
    description: Pick AI commit (no verify)
    command: aicommit2 --no-verify
    context: files
    subprocess: true
